### ISSUE TITLE
super dx?

### ISSUE THREAD

**Issue by aadog** [Sentient111/KernelDrawing#1]
super dx?

**Comment by Sentient111** [comment]
Could you elaborate what you mean by that?

**Comment by aadog** [comment]
does he support imgui painting，
Does he support win11?

**Comment by Sentient111** [comment]
- From what I know you can adjust imgui to use gdi for drawing but I will not provide such code. Making imgui work in kernelmode sounds like a lot of work to me tho since it is meant to run in usermode. If I had to guess then I'd say that making your own menu framework from scratch with some inspiration from other projects would probably be faster than adjusting imgui to it.

- In theory it should work on windows 11, you can check if the functions exist on win11 and update the offsets in nt.h and give it a test I guess.

**Comment by aadog** [comment]
thanks
