### ISSUE TITLE
BSOD PAGE_FAULT_IN_NONPAGED_AREA after shutdown or reboot

### ISSUE THREAD

**Issue by bphucc** [Sentient111/KernelDrawing#3]
Hi, as the title said, I got BSOD when reboot the machine, any fix?

**Comment by gamous** [comment]
@bphucc 
I encountered a similar issue as you, and eventually discovered that this driver relies entirely on kdmapper to load.
The BSOD PAGE_FAULT_IN_NONPAGED_AREA error in win32k is due to the fact that GDI functions require a win32k program context, which is not present in the normal loading process of the driver. https://github.com/TheCruZ/kdmapper/blob/master/kdmapper/intel_driver.hpp#L149
As you can see, kdmapper invokes kernelmode function (include DriverEntry)  by hooking into a function within ntdll and then entering the kernel from usermode ntdll which with the win32k context.
Therefore, in reality, this driver relies on the hooking method within kdmapper to obtain the context for calling win32k, strictly speaking, it is not  drawing without hooking. (lol

**Comment by Sentient111** [comment]
@gamous I create a system thread in the driver entry meaning that even if kdmapper had a valid win32 thread value it would not carry over to the actual drawing code. The whole poc is about getting the win32 value ourselves before drawing.

@bphucc make sure you have the correct offsets for the struct entries in Nt.h. If that does not help feel free to provide more information like how long it takes for the bluescreen to occur and what windows version you are using.
